# Generated by Django 2.2.2 on 2019-06-18 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190611_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hover_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
