# Generated by Django 2.2.2 on 2019-12-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_hover_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link_to_github',
            field=models.URLField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='job',
            name='link_to_website',
            field=models.URLField(default='', max_length=2000),
        ),
    ]
