# Generated by Django 2.2.2 on 2019-12-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20191215_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='link_to_github',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='job',
            name='link_to_website',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
