# Generated by Django 2.2.2 on 2019-07-04 17:10

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', markdownx.models.MarkdownxField()),
            ],
        ),
    ]
