# Generated by Django 2.2.2 on 2019-12-15 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
